name: Build KoBoyOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      # 🆕 Télécharger le .arm64 depuis une release
      - name: 📦 Télécharger le launcher
        run: |
          wget -O KoBoyOS-launcher.arm64 \
          https://github.com/HautotQ/Database_General/releases/latest/download/KoBoyOS-launcher.arm64

      - name: 🔐 Vérifier SHA256
        run: |
          echo "91ffe17c39e2663b0286fc5dbed86cdedb3eccdadf878a84fe9450d910a5bfcd  KoBoyOS-launcher.arm64" | sha256sum -c -
          
      - name: 📦 Installer dépendances
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            git \
            wget \
            cpio \
            unzip \
            rsync \
            bc \
            bison \
            flex \
            libssl-dev \
            libncurses5-dev

      - name: 📥 Télécharger Buildroot
        run: |
          git clone https://github.com/buildroot/buildroot.git
          cd buildroot
          git checkout 2024.02

      - name: ⚙️ Configurer Buildroot
        run: |
          cd buildroot
          make qemu_aarch64_virt_defconfig

      - name: 📁 Préparer overlay + init
        run: |
          mkdir -p buildroot/board/koboye/rootfs-overlay

          # Déplacer le fichier téléchargé
          mv KoBoyOS-launcher.arm64 buildroot/board/koboye/rootfs-overlay/launcher
          chmod +x buildroot/board/koboye/rootfs-overlay/launcher

          # Script init (PID 1)
          cat << 'EOF' > buildroot/board/koboye/rootfs-overlay/init
          #!/bin/sh

          mount -t proc none /proc
          mount -t sysfs none /sys

          echo "KoBoyOS boot..."

          exec /launcher
          EOF

          chmod +x buildroot/board/koboye/rootfs-overlay/init

      - name: 🔧 Config Buildroot
        run: |
          cd buildroot

          echo 'BR2_ROOTFS_OVERLAY="board/koboye/rootfs-overlay"' >> .config
          echo 'BR2_INIT_NONE=y' >> .config

          make olddefconfig

      - name: 🏗️ Build
        run: |
          cd buildroot
          make -j$(nproc)

      - name: 📦 Préparer output
        run: |
          mkdir output-final
          cp -r buildroot/output/images/* output-final/

      - name: ⬆️ Upload OS
        uses: actions/upload-artifact@v4
        with:
          name: KoBoyOS
          path: output-final
